name: Deploy iTERRA Docker Container

on:
  push:
    branches: [ main, production ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t iterra-app:latest .
        
    - name: Deploy iTERRA Container
      run: |
        # Stop existing container
        docker stop iterra-wellness-app 2>/dev/null || true
        docker rm iterra-wellness-app 2>/dev/null || true
        
        # Deploy new container
        docker run -d \
          --name iterra-wellness-app \
          --restart unless-stopped \
          -p 3000:80 \
          -e SUPABASE_ANON_KEY="${{ secrets.SUPABASE_KEY }}" \
          -e NODE_ENV=production \
          iterra-app:latest
          
    - name: Health Check
      run: |
        sleep 15
        curl -f http://localhost:3000/health || exit 1
        
    - name: Deployment Status
      run: |
        echo "✅ iTERRA Wellness Hub deployed successfully!"
        echo "🌐 Container is running on port 3000"
        docker ps --filter name=iterra-wellness-app